name: Run benchmark experiments

on:
  schedule:
    - cron: '0 0 1 * *' # Schedule to run on the 1st day of each month at 12:00 AM UTC
  pull_request: # TODO - Adjust to all
    types:
      - opens
      - synchronize
  push:
    branches:
      - postprocess-automation # TODO - Adjust to all

env:
  FORCE_COLOR: true

jobs:
  run_experiments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install tox
        run: pip install tox
      
      - name: Run tox
        run: tox -e py38