name: Check for new qiskit versions, run benchmark experiments and submit results to metriq.info

on:
  push:
    branches:
      - 'client-update-results' #TODO: Remove this when done debugging CI
  schedule:
    - cron: '0 0 1 * *' # Schedule to run on the 1st day of each month at 12:00 AM UTC

env:
  FORCE_COLOR: true

jobs:
  run_experiment_steps:
    runs-on: ubuntu-latest

    env:
      METRIQ_TOKEN: ${{ secrets.METRIQ_TOKEN}}
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch at least 2 commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tox
        run: pip install tox

      - name: Run experiment steps in tox
        run: tox -ve py311

      - name: Check for new artifacts
        run: |
          cd benchmarking/results
          if git status --porcelain | grep -E "\.csv$" -q; then
            echo "New result files found"
            echo "changed_csv_files=1" >> $GITHUB_ENV
            NEW_BRANCH="automated-branch"
            echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          else
            echo "No result files to process"
            echo "changed_csv_files=0" >> $GITHUB_ENV
          fi
          cd ../../
      
      - name: Create new branch and commit changes
        if: env.changed_csv_files == '1'
        run: |
          # Set bot's token
          export BOT_ACCESS_TOKEN=${{ secrets.BOT_ACCESS_TOKEN }}

          # Config Git with bot's credentials
          git config user.name "${{ secrets.BOT_USERNAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"

          # Create new branch
          git checkout -b ${{ env.NEW_BRANCH }}
          cd benchmarking/results

          # List new and deleted CSV files and save output
          git status --porcelain | awk '($1 ~ /^[?][?]/ || ($1 == "A" || $1 == "D")) && $2 ~ /\.csv$/{print$2}' > ../../csv_changes.txt
          cd ../../

          # Loop through the saved list items and add them to staging
          while IFS= read -r csv_file; do
            git add "$csv_file"
          done < csv_changes.txt

          # Commit and push changes
          git commit -m "Add new result files during workflow"
          git push origin ${{ env.NEW_BRANCH }}
        env:
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Create new PR for new artifacts
        if: env.changed_csv_files == '1'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          title: "Add new result files"
          source_branch: ${{ env.NEW_BRANCH }}
          destination-branch: "main"
          delete-branch: true
          

