name: Run benchmark experiments

on:
  schedule:
    # - cron: '0 0 1 * *' # Schedule to run on the 1st day of each month at 12:00 AM UTC
    - cron: '0 * * * *' # Schedule to run every hour for now

jobs:
  run_experiments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install tox
        run: pip install tox
      
      - name: Run tox
        run: tox -e py38